development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: lotipico_dev
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: lotipico_test
  pool: 5
  username: root
